### PR TITLE
Fix/emit errors with no errors

### LINKED ISSUE #69: emitError: false emits empty warning
Using latest code, if I set the config `emitErrors: false` then I see the webpack build passes but with a warning. This appears to be [due to line 22 of run-compilation.js](https://github.com/JaKXz/stylelint-webpack-plugin/blob/master/lib/run-compilation.js#L22-L28) where the result from the ternary should be `[]` rather than `results`

screen shot 2017-02-22 at 15 03 36

### PR DESCRIPTION
**Pull request by JaKXz**
Fixes #69.

### CODE REVIEW

**Comment by JaKXz** [comment]
@nijk if you could try `npm install JaKXz/stylelint-webpack-plugin#fix/emitErrors-with-no-errors`, it should fix the error you reported earlier.

**Comment by nijk** [comment]
@JaKXz Thanks for looking at this so quickly. I can confirm the fix works for the reported issue. Nice use of Ramda! Any chance you could tag master/publish to NPM so that I can pull this into my project by version?

**Comment by JaKXz** [comment]
@nijk will do so mid-next week when I have OSS cycles again - in the meantime I'm hoping folks can find bugs like you did :)

**Comment by JaKXz** [comment]
`+ stylelint-webpack-plugin@0.7.0` published! Thanks for your patience.

**Pull request merged**
