### PR TITLE
Refactor/lint dirty modules only

### PR DESCRIPTION
**Pull request by JaKXz**
@sergesemashko to get a better handle on the code from #53 I took a stab at [some minor nits &] refactoring and staying green :) let me know if there's anything that concerns you. 

Thanks!

### CODE REVIEW

**Comment by sergesemashko** [comment]
looks good to me 👍

**Comment by JaKXz** [comment]
Are there any other test cases you can think of?

**Comment by sergesemashko** [comment]
actually, can't think of anything else. all cases that I'm aware of are covered

**Comment by sergesemashko** [comment]
@JaKXz, all works fine on my local with and without lintDirtyModulesOnly flag.

The unrelated thing, I'm seeing that messages are duplicated when `quiet` flag is set to false - http://take.ms/GQb4g.
I think, [this line](https://github.com/JaKXz/stylelint-webpack-plugin/blob/master/lib/run-compilation.js#L30) is the reason

**Comment by JaKXz** [comment]
@sergesemashko would you mind making a new issue for that? I think I have a fix, I'll make a PR soon.

**Pull request merged**
